### ISSUE TITLE
Look into how SourceMD does it

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#10]
https://tools.wmflabs.org/sourcemd/new_resolve_authors.php?doit=Look+for+author&name=Jane+Brown

**Comment by arthurpsmith** [comment]
@Daniel-Mietchen - Yes, it's based on new_resolve_authors - I've been chatting with Magnus about it. Magnus thought it should be thrown out and start over, but I think it's not a bad start.

**Comment by arthurpsmith** [comment]
See https://tools.wmflabs.org/author-disambiguator/?name=Jane+Brown&doit=Look+for+author for the new version - it's safe to click "Do It" as unlike SourceMD it doesn't immediately batch it. I should probably change the "Do It" button label...

**Comment by arthurpsmith** [comment]
I changed the button label - closing this!
