### ISSUE TITLE
Allow for more publication types to be curated

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#103]
E.g. RFCs like [RFC 1425: SMTP Service Extensions (Q47471236)](https://www.wikidata.org/wiki/Q47471236).

**Comment by Daniel-Mietchen** [comment]
Clinical trials would be useful too. For instance, we would like to express that [Laura J. Havrilesky (Q87009294)](https://www.wikidata.org/wiki/Q87009294) is the Principal Investigator of the trial [Cost of Cancer Risk Management in Women at Elevated Genetic Risk for Ovarian Cancer Who Participated on GOG-0199 (Q63321691)](https://www.wikidata.org/wiki/Q63321691), according to https://clinicaltrials.gov/ct2/show/NCT01445275 . We are in the process of capturing that information for Wikidata, and being able to use the Author Disambiguator for that would be great. 

One issue here is that we may not be using P2093 (author name string) and P50 (author) but something like director/manager (P1037) or a yet-to-be-proposed property like "Principal Investigator", likely a long with a string variant.

**Comment by Daniel-Mietchen** [comment]
Theses would be a natural fit too, e.g. as per https://author-disambiguator.toolforge.org/work_item_oauth.php?id=Q59574504 .

**Comment by arthurpsmith** [comment]
So I'm not constraining publication type at all in the queries - it's just looking for anything with a P2093 that matches. I don't understand why your RFC 1425 example doesn't seem to show up when I query for the unmatched authors; I guess I'll try to get to the bottom of that.

To do other things like director/manager/editor etc. would require some very different work - I guess I'll look at that under #143 and focus this one on why RFC1425 (and similar) is not showing up...

**Comment by arthurpsmith** [comment]
ah, it turns out it WAS in the list - just the display by default uses the title (P1476) instead of the English label, and the title was missing the "RFC 1425: " prefix. So I think all is well as far as RFC's go, they can be matched just fine. As mentioned the other issues are quite different; I'll close this one and hopefully look at #143 soon.
