### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#104]
I cannot access any page under https://tools.wmflabs.org/author-disambiguator/ this morning.

**Comment by Daniel-Mietchen** [comment]
It works again for me. Not sure what it was, but closing this for now.

**Comment by arthurpsmith** [comment]
I didn't receive any notice about a problem; the same kubernetes "pod" seems to be running, so it wasn't restarted by somebody. Not sure.

I do wonder if our current users are aware of the ability to restart batches, clear errors, etc? Have you tried this yourself? Just go to the "Batches" link at the top to see your work, delete ones that have finished, and restart ones that didn't finish properly. Let me know if you see problems with the way this works or have suggestions for a better UI for it...
