### ISSUE TITLE
Batches show as READY when in fact they have been completed

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#111]
Opposite behaviour with respect to #110 but perhaps the same underlying issue.

Most recent example: https://tools.wmflabs.org/author-disambiguator/batches_oauth.php?id=7652b2 ,
triggerd by 
https://tools.wmflabs.org/author-disambiguator/names_oauth.php?name=Marek%20Cieplak

![Screenshot_2019-12-28 Author Disambiguator(1)](https://user-images.githubusercontent.com/465923/71551428-40ba6c00-29b5-11ea-87f8-ef3e1f8c28c0.png)
![Screenshot_2019-12-28 Related changes - Wikidata](https://user-images.githubusercontent.com/465923/71551427-40ba6c00-29b5-11ea-97b3-579cf8480ba4.png)

**Comment by Daniel-Mietchen** [comment]
Reloading the page provided the correct information:
![Screenshot_2019-12-28 Author Disambiguator(3)](https://user-images.githubusercontent.com/465923/71551445-ea99f880-29b5-11ea-8113-94e2b9b66ee8.png)

**Comment by arthurpsmith** [comment]
The page for a specific batch should reload automatically via a javascript action until everything's done, but maybe sometimes that doesn't work? Anyway, feel free to reload the batch page any time. I don't think there's anything really to be done here unless this seems to be a frequent bug?
