### ISSUE TITLE
Edits triggered by "Merge these author records" should be queueable

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#124]
Right now, maxlag is too high for edits, so 
triggering the "Merge these author records" button at
https://tools.wmflabs.org/author-disambiguator/work_item_oauth.php?id=Q53422751
<img width="1154" alt="Screen Shot 2020-03-06 at 19 07 12" src="https://user-images.githubusercontent.com/465923/76131993-b3ac1880-5fde-11ea-8bfe-73f85cce03fc.png">

yields
```
Something went wrong? Error code: maxlag
Failed to update Q53422751
```
and a ```Try again``` button.

<img width="999" alt="Screen Shot 2020-03-06 at 19 07 35" src="https://user-images.githubusercontent.com/465923/76132004-bf97da80-5fde-11ea-8984-184c42d2aa01.png">

Making use of that latter button would require having a tab open until maxlag is back in good waters, which may take a while, so it would be good if these edits could be sent to the queue just like the other edits.

**Comment by arthurpsmith** [comment]
I've made this change now!

**Comment by Daniel-Mietchen** [comment]
Does not work for me at 
https://tools.wmflabs.org/author-disambiguator/work_item_oauth.php?id=Q45845482

![Screenshot_2020-04-02 Author Disambiguator(3)](https://user-images.githubusercontent.com/465923/78315656-a6c20c80-752b-11ea-8a84-41e0ef613604.png)

![Screenshot_2020-04-02 Author Disambiguator(4)](https://user-images.githubusercontent.com/465923/78315666-ade91a80-752b-11ea-85ee-324ad60f80fd.png)

**Comment by Daniel-Mietchen** [comment]
Got the example to merge, presumably thanks to maxlag not being overly high.
