### ISSUE TITLE
Problem with "Ø" in author name string

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#127]
https://tools.wmflabs.org/author-disambiguator/names_oauth.php?name=Bernhard%20%C3%98%20Palsson
currently gives 0 hits, even though a [count of works with that author name string](https://w.wiki/KjM) currently gives 137.

I suspect this is not unique to the letter "Ø" but probably affects certain sets of special characters.

![Screenshot_2020-03-18 Wikidata Query Service](https://user-images.githubusercontent.com/465923/77019991-a7b64400-6958-11ea-9618-7cb8dbf5ee38.png)
![Screenshot_2020-03-18 Author Disambiguator](https://user-images.githubusercontent.com/465923/77019993-a8e77100-6958-11ea-9a34-e63196c5f4f2.png)

**Comment by arthurpsmith** [comment]
Could be a number of issues, I'll check into it!

**Comment by Daniel-Mietchen** [comment]
[Here](https://query.wikidata.org/#%0ASELECT%0A%20%20%23%20Number%20of%20works%20on%20the%20topic%20with%20the%20author%20name%20string%0A%20%20%3Fcount%0A%0A%20%20%23%20Number%20of%20works%20with%20the%20author%20name%20string%0A%20%20%3Fcount1%0A%0A%20%20%23%20Author%20as%20a%20string%0A%20%20%3Fauthorstring%0A%0A%20%20%23%20Build%20URL%20to%20the%20Author%20disambiguator%20tool%0A%20%20%28CONCAT%28%0A%20%20%20%20%20%20%27https%3A%2F%2Ftools.wmflabs.org%2Fauthor-disambiguator%2Fnames_oauth.php%3Fname%3D%27%2C%0A%20%20%20%20%20%20ENCODE_FOR_URI%28%3Fauthorstring%29%29%20AS%20%3Fresolver_url%29%0AWITH%20%7B%0A%20%20SELECT%20DISTINCT%20%3Fwork%20%3Fauthorstring%20WHERE%20%7B%0A%20%20%20%20%3Fwork%20wdt%3AP2093%20%3Fauthorstring%20.%0A%20%20%20%20FILTER%20CONTAINS%28%3Fauthorstring%2C%20%22%C3%98%22%29.%20%20%0A%20%20%7D%0A%20%20LIMIT%20100%0A%7D%20AS%20%25works%0AWITH%20%7B%0A%20%20SELECT%0A%20%20%20%20%28COUNT%28DISTINCT%20%3Fwork%29%20AS%20%3Fcount%29%0A%20%20%20%20%28COUNT%28DISTINCT%20%3Fwork1%29%20AS%20%3Fcount1%29%0A%20%20%20%20%3Fauthorstring%0A%20%20WHERE%20%7B%0A%20%20%20%20INCLUDE%20%25works%0A%20%20%20%20%3Fwork1%20wdt%3AP2093%20%3Fauthorstring%20.%0A%20%20%7D%0A%20%20GROUP%20BY%20%3Fauthorstring%0A%7D%20AS%20%25result%0AWHERE%20%7B%0A%20%20INCLUDE%20%25result%0A%7D%0AORDER%20BY%20DESC%28%3Fcount%29%20DESC%28%3Fcount1%29%0ALIMIT%2050%0A%0A%20%20%0A) are some more cases with ```Ø```.

**Comment by arthurpsmith** [comment]
Sorry to be slow getting to this - the recent fix for cyrillic characters should also have fixed this. I checked the 'Bernhard Ø Palsson' case and it seems to work fine now!

**Comment by Daniel-Mietchen** [comment]
Looks fixed.
