### ISSUE TITLE
Keep track of "Unordered authors" errors

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#128]
so as to allow for dedicated curation, as we currently do not have good mechanisms for exposing such problems.

For instance, https://tools.wmflabs.org/author-disambiguator/batches_oauth.php?id=e611dd
initially gave that error for https://www.wikidata.org/wiki/Q27824784 ,
and upon checking [at the source](https://doi.org/10.1056/NEJMoa012914), I noticed that other authors are missing too.

**Comment by Daniel-Mietchen** [comment]
Another example that I found via such an error is
https://tools.wmflabs.org/author-disambiguator/work_item_oauth.php?id=Q27931123 .

Here, I tried to set the author numbers, but that did not work.

Also, the stats are wrong in this case.

<img width="1147" alt="Screen Shot 2020-03-19 at 04 31 41" src="https://user-images.githubusercontent.com/465923/77047119-9e4dcb80-699a-11ea-99bd-bb511891b540.png">

**Comment by Daniel-Mietchen** [comment]
Here is another one:
https://www.wikidata.org/wiki/Q84361157

**Comment by arthurpsmith** [comment]
In general I'm not handling authors with missing "series ordinal" qualifiers well, there's another issue open related to this. However, you can set the values here if you check the "renumber authors" box at the top and hit the "Get author links for work" button again.

**Comment by Daniel-Mietchen** [comment]
Interesting. I had tried the "Renumber authors?" box before but did not think of re-running the "Get author links for work" routine. Makes sense, though &mdash; thanks!

**Comment by arthurpsmith** [comment]
Further work on unordered authors will be done on #110 - closing this one.
