### ISSUE TITLE
Suggestion: handle multiple authors simultaneously

### ISSUE THREAD

**Issue by arthurpsmith** [arthurpsmith/author-disambiguator#13]
Suggestion from Tony Catapano at WikiCite meeting: allow entry of multiple authors for match, when they are typically co-authors:
* find all papers they are both (all) on
* generate QuickStatements to replace both (all) author string records with the author items

**Comment by Daniel-Mietchen** [comment]
Here is a useful query for such cases: https://twitter.com/MagnusManske/status/973840728852975617

**Comment by Daniel-Mietchen** [comment]
I have set up a Listeria list to experiment with that a bit: https://www.wikidata.org/wiki/Wikidata:WikiProject_Source_MetaData/Wikidata_lists/Author_name_strings_that_are_on_multiple_papers_with_at_least_three_identical_co-authors .

**Comment by arthurpsmith** [comment]
I've been thinking a bit about how to do this - main problem to me is how to lay out the page in a way that makes it usable and not much work for the most common cases. I may experiment with a completely new layout - anyway it would be a separate page from the current main "index.php" page...

**Comment by arthurpsmith** [comment]
Ok - done! Check it out at (for example):
https://tools.wmflabs.org/author-disambiguator/match_multi_authors.php?limit=50&id=Q56708301+Q53467544
