### ISSUE TITLE
"Restart batch" button does not work

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#130]
See screenshot of my recent batches. I clicked that button for all of them, to no effect.
<img width="1123" alt="Screen Shot 2020-03-31 at 20 25 33" src="https://user-images.githubusercontent.com/465923/78087066-cf140480-738d-11ea-8b22-985acfc6e93a.png">

**Comment by arthurpsmith** [comment]
Sorry about that - side-effect of recent queueing change. It should work now!

**Comment by Daniel-Mietchen** [comment]
Yes, looks fine &mdash; thanks!
