### ISSUE TITLE
On work pages, allow identifying individual authors directly

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#131]
For instance, here, I know it's [Rosalynn Carter (Q219353)](https://www.wikidata.org/wiki/Q219353) and could state that right away but right now I would have to go via
- https://tools.wmflabs.org/author-disambiguator/names_oauth.php?limit=50&name=Carter+R (which did not find the paper) and then https://tools.wmflabs.org/author-disambiguator/names_oauth.php?limit=500&name=Carter+R
- or do it manually on the item itself

<img width="1281" alt="Screen Shot 2020-04-01 at 21 11 55" src="https://user-images.githubusercontent.com/465923/78200712-8035a000-745d-11ea-8924-182d20387f1c.png">

**Comment by Daniel-Mietchen** [comment]
Perhaps there could even be an option to suggest items of potential authors based on co-occurring items or strings. This usually works nicely if multiple co-authors have already been identified, as in the example pasted in below.

![Screenshot_2020-04-01 Author Disambiguator](https://user-images.githubusercontent.com/465923/78202788-3c459980-7463-11ea-885f-8bbc166ca5b3.png)

**Comment by Daniel-Mietchen** [comment]
Some relevant query examples: https://www.wikidata.org/wiki/Wikidata:WikiProject_Source_MetaData/Wikidata_lists/Author_name_strings_that_are_on_multiple_papers_with_at_least_three_identical_co-authors

**Comment by arthurpsmith** [comment]
Hi @Daniel-Mietchen - have you tried the "Suggest matches?" toggle at the top of the page? Also I find that "Use "stated as" names" is helpful for this. But I agree that it would be nice to have a mechanism that works even when there are no such matching suggestions.

**Comment by Daniel-Mietchen** [comment]
Ha, I hadn't tried "Suggest matches" in a long while, and it did provide some useful suggestions. Thanks!

![Screenshot_2020-04-02 Author Disambiguator](https://user-images.githubusercontent.com/465923/78305950-31950e00-7510-11ea-8065-21b483f3832f.png)

**Comment by Daniel-Mietchen** [comment]
Trying to actually do a matching resulted in #132 .

**Comment by arthurpsmith** [comment]
I think this is basically completely handled now with "suggest matches" and the new author lists feature. If there's something more needed please feel free to open a new issue!
