### ISSUE TITLE
Edits triggered by "Match selected authors" should be queuable

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#132]
similar issue to #124 .

![Screenshot_2020-04-02 Author Disambiguator(1)](https://user-images.githubusercontent.com/465923/78306314-124ab080-7511-11ea-8927-22c93651e680.png)

yields

![Screenshot_2020-04-02 Author Disambiguator(2)](https://user-images.githubusercontent.com/465923/78306325-18409180-7511-11ea-9c56-b0b13cf70b43.png)

**Comment by arthurpsmith** [comment]
All the oauth edits are now queued... hopefully the way this works makes sense. Let me know any problems though!

**Comment by Daniel-Mietchen** [comment]
Looks good so far - https://tools.wmflabs.org/author-disambiguator/batches_oauth.php?id=5a843cd2 has entered the queue, but the queue is long.
