### ISSUE TITLE
Warning: QID not found

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#136]
The tool seems to have lots of issues right now, and as I suspect/ hope these are mostly transient, I am not sure which ones to post, but this one is at least interesting, as the item
https://www.wikidata.org/wiki/Q44995027
does exist and is properly tagged as "scholarly article".

<img width="1112" alt="Screen Shot 2020-04-05 at 22 32 13" src="https://user-images.githubusercontent.com/465923/78518091-6661c900-778d-11ea-8f7a-0cc5d93c2c1e.png">

**Comment by arthurpsmith** [comment]
Wikidata query server error. Not really anything to do about it...?
