### ISSUE TITLE
Apostrophe causes problem in link from non-OAuth to OAuth version

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#138]
E.g. in
https://tools.wmflabs.org/author-disambiguator/?doit=Look+for+author&name=Andrea%20%27t%20Mannetje&filter=wdt%3AP50+wd%3AQ37392568 ,
the link goes to 
https://tools.wmflabs.org/author-disambiguator/names_oauth.php?name=Andrea .

**Comment by arthurpsmith** [comment]
Fixed!
