### ISSUE TITLE
Cyrillic letters not recognized in search?

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#139]
On https://tools.wmflabs.org/scholia/venue/Q85793224/missing , the first panel currently lists 2 papers for the string "А. А. Абрикосов", but the corresponding call
https://tools.wmflabs.org/author-disambiguator/names_oauth.php?name=%D0%90.%20%D0%90.%20%D0%90%D0%B1%D1%80%D0%B8%D0%BA%D0%BE%D1%81%D0%BE%D0%B2&fuzzy=0&wbsearch=0&limit=50&use_name_strings=0&name_strings=
does not yield any results, though a [variant](https://w.wiki/PNH) of the Scholia query identifies
[Q92314336](https://www.wikidata.org/w/index.php?title=Q92314336&oldid=1168584151)
and
[Q92314273](https://www.wikidata.org/w/index.php?title=Q92314273&oldid=1168556447)
as the two works in question.

I will fix these manually but am attaching relevant screenshots here for debugging what looks to me to be a UTF encoding problem.

![Screenshot_2020-04-28 Author Disambiguator](https://user-images.githubusercontent.com/465923/80541367-0966c680-8979-11ea-8c74-923d87e86116.png)
![Screenshot_2020-04-28 Scholia(1)](https://user-images.githubusercontent.com/465923/80541373-0bc92080-8979-11ea-932e-e2f6e3bb574d.png)

**Comment by Daniel-Mietchen** [comment]
Just for the record: same issue with "Э. А. Канер" ([Q92314315](https://www.wikidata.org/w/index.php?title=Q92314315&oldid=1168584471) and [Q92314258](https://www.wikidata.org/w/index.php?title=Q92314258&oldid=1168557237)).

**Comment by arthurpsmith** [comment]
Thanks - I'm looking at this... definitely seems to be an issue.

**Comment by arthurpsmith** [comment]
Actually, this appears to be because the author name string never makes it into WDQS servers at all! Looks like a bug there - I'll report it.

Try SPARQL: SELECT ?p ?v WHERE { wd:Q92314336 ?p ?v .  }

It doesn't list the author name string statements at all!

**Comment by arthurpsmith** [comment]
Hmm, though the strings are there for "Э. А. Канер"

**Comment by arthurpsmith** [comment]
Ok, should be fixed now - try "Э. А. Канер" again. Also Marzanna Łusiak-Szelachowska should work properly now too.

**Comment by Daniel-Mietchen** [comment]
Looks good!
