### ISSUE TITLE
Tootltips (or instructions) on some key terms

### ISSUE THREAD

**Issue by TS404** [arthurpsmith/author-disambiguator#144]
Many users of this tool will not be well-versed in the technical terms included as options (e.g. Fuzzy match, Wikibase search. Specify name strings). Simple definitions of what they mean in this context would be valuable (either as tooltips, or a separate instruction readme or vignette series).

**Comment by arthurpsmith** [comment]
Thanks for the suggestion - I've actually just started a documentation page on-wiki: https://www.wikidata.org/wiki/Wikidata:Tools/Author_Disambiguator - where I'll try to provide more detailed documentation. But adding some of that in abbreviated for as tooltips is a good idea too!

**Comment by arthurpsmith** [comment]
Ok, I added a few tooltips (the ones suggested plus some similar spots for checkboxes on the authors and works pages). If you have any more specific places you think these are needed, feel free to open a new github issue!
