### ISSUE TITLE
Unscramble the bottom sections

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#147]
example: https://author-disambiguator.toolforge.org/author_item_oauth.php?limit=50&id=Q64385777
![Screenshot_2020-10-06 Author Disambiguator(1)](https://user-images.githubusercontent.com/465923/95257303-1b834580-07f2-11eb-9266-162452369ef3.png)

**Comment by arthurpsmith** [comment]
@carlinmack proposed fix did it, though not quite where the pull request put the fix. Closing!
