### ISSUE TITLE
Warning: A non-numeric value encountered in /data/project/author-disambiguator/public_html/lib/clustering2.php on line 283

### ISSUE THREAD

**Issue by davidhicks** [arthurpsmith/author-disambiguator#148]
Many instances of the error:
Warning: A non-numeric value encountered in /data/project/author-disambiguator/public_html/lib/clustering2.php on line 283

To reproduce, use the following URL/query:
https://author-disambiguator.toolforge.org/names_oauth.php?precise=1&name=J.+Arkko&doit=Look+for+author&limit=500&filter=wdt%3AP31+wd%3AQ212971

**Comment by arthurpsmith** [comment]
Looks like this was a problem with precise clustering for unordered authors. Now fixed!
