### ISSUE TITLE
Author disambiguator won't function

### ISSUE THREAD

**Issue by Kpjas** [arthurpsmith/author-disambiguator#149]
![image](https://user-images.githubusercontent.com/553156/98782023-934b1e00-23f7-11eb-86f6-37901bb687b4.png)

Just after clicking the  "Link selected works to author" nothing is being performed.
--

**Comment by Daniel-Mietchen** [comment]
Just came here to report the same. [Here](https://youtu.be/CfjoRMaRpEY) is a brief demo.

**Comment by arthurpsmith** [comment]
Wikitech did something with the tools db yesterday, it sounds like maybe something  needs  to be restarted... looking at it now!

**Comment by arthurpsmith** [comment]
Still seems to be in read-only mode - here's the error I'm seeing:
"The MariaDB server is running with the --read-only option so it cannot execute this statement"
I'll query what's going on...

**Comment by arthurpsmith** [comment]
Phabricator ticket: https://phabricator.wikimedia.org/T266587

**Comment by arthurpsmith** [comment]
Looks like it will be several more hours before the read-only mode is removed. I'm hoping things will just come back after that point...

**Comment by Daniel-Mietchen** [comment]
Read-only mode has been [ended](https://phabricator.wikimedia.org/T266587#6619766).

[Test batch](https://author-disambiguator.toolforge.org/batches_oauth.php?id=8a0ecf73).

**Comment by arthurpsmith** [comment]
Ok, read-only mode is gone and things seem to be working again. However, there should be a clearer error  message for this, or some  way of putting the service into read-only mode, so I'm going to leave this issue open to deal with that...

**Comment by arthurpsmith** [comment]
I added checks to the initial database update attempts which should produce a suitable warning now. Closing...
