### ISSUE TITLE
Author Disambiguator down due to Tools db maintenance

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#151]
Just to keep track of it, so we have some data when this happens again.

Odd typos in the notification though.

<img width="1040" alt="Screen Shot 2020-12-16 at 21 05 45" src="https://user-images.githubusercontent.com/465923/102434393-acd91a00-3fe2-11eb-8f06-7881941d7d06.png">

**Comment by arthurpsmith** [comment]
Oops. I'll fix that!

**Comment by arthurpsmith** [comment]
Typo was fixed by the way. Not that anyone can see it right now. I guess this is ok to close?

**Comment by Daniel-Mietchen** [comment]
Yeah. I think this outage lasted on the order of half a day.
