### ISSUE TITLE
David S, Hibbett

### ISSUE THREAD

**Issue by MargaretRDonald** [arthurpsmith/author-disambiguator#152]
I disambiguated numerous article and assigned them to one of the two wikidata items for David S. Hibbett.  (I think where he was described as a  U.S. mycologist.). Having done so, I discovered that his English article was linked to David Hibbett (American mycologist) and that there were three wikidata items for David S. Hibbett. I did as you do, and merged the two later items to David Hibbett.  The articles disambiguated to David S. Hibbett are not showing yet as being associated with David Hibbett  in the scholia template.  These should have been redirected at the same time as the merges.  Hoping you can sort out what has happened or whether I should just wait while wikidata syncs (?).  Regards, MargaretRDonald

**Comment by Daniel-Mietchen** [comment]
@MargaretRDonald This looks solved now on their [Scholia profile](https://scholia.toolforge.org/author/Q5234971), thanks to [these edits](https://www.wikidata.org/w/index.php?title=Special:Contributions/KrBot&offset=20201228042628&target=KrBot&limit=129).

**Comment by MargaretRDonald** [comment]
Thanks for getting back to me.  (I was a bit anxious. And I am glad that I
raised it since it did require some attention.)  The merge failed to do the
necessary redirects...)
Cheers,
Margaret

**Comment by arthurpsmith** [comment]
Yes,  Wikidata does not automatically replace redirected item values in statements with the new item, so the bot Krbot checks for such things and moves them after a few days.

**Comment by MargaretRDonald** [comment]
Thanks Arthur.  Thank gof for your bots

Margaret Donald BA (Hon), M. App Stat, Ph.D, AStat
Statistician, Anne Clements & Associates
