### ISSUE TITLE
503 errors

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#153]
I am getting 503 errors like this right now, while other Toolforge tools like Scholia do not seem to be affected.

<img width="901" alt="Screen Shot 2021-01-03 at 17 53 59" src="https://user-images.githubusercontent.com/465923/103490851-aae9c600-4dec-11eb-8720-3c071d6cd7ba.png">

**Comment by arthurpsmith** [comment]
Sorry about this - I restarted the server, can you see if it's still happening? From the error logs it looks like there was some resource issue on the server, I'll check on it some more tomorrow.

**Comment by Daniel-Mietchen** [comment]
@arthurpsmith I tried multiple times since I opened the ticket but have not seen any Author Disambiguator page that would actually load.

**Comment by Daniel-Mietchen** [comment]
It's back now. Thanks!

**Comment by arthurpsmith** [comment]
This appears to be related  to a toolforge problem the last few days.  I opened  Phabricator  ticket T271181 on  our specific issue. However, things seem to be getting better again. I'm going to close this - please comment on the Phabricator ticket if you see this continue to happen.
