### ISSUE TITLE
Add link from the tool to the code repo here

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#16]
So that people can find the repo more easily to provide comment or other contributions.

**Comment by arthurpsmith** [comment]
Definitely, I'll try to get that in ASAP!

**Comment by arthurpsmith** [comment]
Hmm, using the existing navbar led me into CSS problems I couldn't figure out just now, so I've just added links in the footer. Layout reformatting should be tackled at some point...
