### ISSUE TITLE
Looking for a way to match authors and theses items in bulk 

### ISSUE THREAD

**Issue by HelsKRW** [arthurpsmith/author-disambiguator#172]
Hi, I'm hoping someone might be able to help with use of the Author Disambiguator Tool.  
I have previously used it to match individual authors with their works, but am wondering if it's possible to do this for a batch of authors and items.  
I have previously created Wikidata items for institutional theses records, but many of these contain author name string statements as the authors did not already have Qids. 
I am now creating Qids for those missing authors, so I have a set of Qids for authors newly added to Wikidata, and a set of Qids for theses already added to Wikidata. 
I would like to run a batch edit which would change all the author name string statements to author statements on the set of thesis Qids.   I can see how to do this one at a time, but is there a way I can do it in bulk for a set?  

For example these 5 Qids are for authors.  Q111729020  Q111729021  Q111729022  Q111729023  Q111729024
These 5 Qids are for their thesis Q101526502  Q101421744  Q101421634  Q101421720  Q100969241  

Is there a way to edit those 5 thesis Qids in bulk so that the author name string statement is replaced with the author Qid?  

I have had a look at the Lists functionality but not been able to work out how to do it.    
Thanks in advance for any help.  
Best wishes 
Helen

**Comment by arthurpsmith** [comment]
Hi Helen - the Lists functionality is intended for groups of coauthors, so where there are multiple authors who have together been involved in many papers together. I've used it mostly in particle physics where we have hundreds of authors who publish hundreds of papers with essentially the same author list, or overlapping ones, over a period of years.

Anyway, the thesis problem is a quite different one as there's generally just one author for each. I'll have to think about a way to handle that better here; for now I don't think there's any easy way to use this tool for that use case.
