### ISSUE TITLE
On the pages for author items, show the "stated as" data

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#180]
E.g. on pages like
https://author-disambiguator.toolforge.org/author_item_oauth.php?id=Q55762421 for someone named "Christopher J Moore" (screenshot below),
it would be useful to see all the cases where "stated as" starts with a "B" (as in https://author-disambiguator.toolforge.org/names_oauth.php?doit=Look+for+author&name=B%20C%20Moore ; screenshot below too), which may hint at mismatches.

Ideally, it would also be possible to sort and/ or filter by the "stated as" strings.

![Screenshot 2022-12-01 at 11-29-21 Author Disambiguator](https://user-images.githubusercontent.com/465923/205030334-953f2dc0-1a66-4f37-a00b-1dd24be773d5.png)

![Screenshot 2022-12-01 at 11-29-07 Author Disambiguator](https://user-images.githubusercontent.com/465923/205030225-2dd79020-7cf3-474f-b828-d2e2bf83ab25.png)

**Comment by arthurpsmith** [comment]
Hi - I've updated this so that the "stated as" name strings are now links to pages where the SPARQL filter is used to show papers that have that stated as value for that author. Let me know if you think this addresses the problem. You can definitely see where Christopher Moore has been incorrectly linked!

**Comment by Daniel-Mietchen** [comment]
I just tried the sample query from above and am now getting new errors:
```Warning: curl_multi_setopt(): CURLPIPE_HTTP1 is no longer supported in /data/project/author-disambiguator/public_html/lib/borrowed_utilities.php on line 440```


![image](https://user-images.githubusercontent.com/465923/205741802-0c48e524-7a0d-442d-9bd2-f070d987e077.png)

**Comment by Daniel-Mietchen** [comment]
Thanks - this does what I wanted.
