### ISSUE TITLE
Warning: session_write_close(): Failed to write session data

### ISSUE THREAD

**Issue by VDK** [arthurpsmith/author-disambiguator#182]
I'm getting a lot of PHP error messages when I try to log in. At just the landing page it's:

Notice: Trying to access array offset on value of type null in /data/project/author-disambiguator/public_html/lib/session_handler.php on line 50

Warning: session_write_close(): Failed to write session data using user defined save handler. (session.save_path: /var/lib/php/sessions) in /data/project/author-disambiguator/public_html/lib/wikidata_oauth.php on line 111

Not managing to log in atm. After I authorize the use of my Wikimedia account I get a blank page that has just this error. I'm still not logged in when I go to the landing page.

**Comment by arthurpsmith** [comment]
Hi - unfortunately last night the "toolsdb" toolforge database, which this application relies on, was accidentally taken offline for about 30 minutes. It is working now though. Thanks for the report!

**Comment by VDK** [comment]
Before loving in I still get the php error at the top of the page:

Notice: Trying to access array offset on value of type null in /data/project/author-disambiguator/public_html/lib/session_handler.php on line 50

I am able to log in though
