### ISSUE TITLE
On author pages, link aliases to their disambiguation pages

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#188]
On author pages like
https://author-disambiguator.toolforge.org/author_item_oauth.php?id=Q450514 ,
aliases like "A. G. TANSLEY" are listed. They are currently just strings but these strings could be hyperlinked to their respective Author Disambiguator pages like https://author-disambiguator.toolforge.org/names_oauth.php?doit=Look+for+author&name=A.%20G.%20TANSLEY .

**Comment by arthurpsmith** [comment]
Yeah, look at that, I wonder why I linked the stated as labels but not the alias labels. Seems useful. I should probably look at some of the other open issues here too!

**Comment by arthurpsmith** [comment]
Ok, done! Closing this.

**Comment by arthurpsmith** [comment]
By the way, the stated as labels link out to a more detailed author item search page that's just looking at items using those particular labels. This was something I commonly ran across after Magnus's bot mismatched a lot of authors using just last names. So it was going somewhere different than this, but both make sense.
