### ISSUE TITLE
No response to issues and PRs?

### ISSUE THREAD

**Issue by dpriskorn** [arthurpsmith/author-disambiguator#198]
I see a merge request not being responded to for months.
No clear information about who maintains this tool.
No reaction from maintainer to issues.

**Comment by arthurpsmith** [comment]
and yet somehow the repo was updated two weeks ago.

Issues do cross my radar. I'll get to them when I can. Feel free to provide more pull requests. I've had some issues in the past with some pull requests here so they do need time to review, which I've not had time for recently.
