### ISSUE TITLE
Get error when seaching for name after login

### ISSUE THREAD

**Issue by dpriskorn** [arthurpsmith/author-disambiguator#199]
Error retrieving token: mwoauthdatastore-request-token-not-found
![image](https://github.com/user-attachments/assets/3ee43152-b0b6-41d6-8b75-640d2e1d1d4f)
got this after pressing blue button here
![image](https://github.com/user-attachments/assets/346131d7-1a78-4015-aa7b-a83eb3c21236)

**Comment by dpriskorn** [comment]
After reload it worked fine.

**Comment by arthurpsmith** [comment]
Looks like a Mediawiki OAuth issue - it happens from time to time. Toolforge services aren't perfect, I don't see anything to do here. Closing.
