### ISSUE TITLE
Under "Potential author items", link to Reasonator instead of Wikidata item directly

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#21]
That way, it is simpler to get an overview of the things that are useful for disambiguation.

**Comment by arthurpsmith** [comment]
Actually I've added a link to a new "identified author" page, which lists their papers and links to WD, Scholia and Reasonator, both for the potential authors and for identified authors listed in the publications list. Also added considerably more info on each author in the potential authors list. Closing...
