### ISSUE TITLE
When using the filter, it would be good to have an option to apply it as well to the potential authors

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#31]
e.g. when using 
https://tools.wmflabs.org/author-disambiguator/?doit=Look+for+author&name=Li%20Li&filter=wdt%3AP921+wd%3AQ2092064
to look for papers by "Li Li" about hemophilia A, it would be useful to surface/ highlight in the "potential author items" section all those that have already published stuff on the same topic.

**Comment by Daniel-Mietchen** [comment]
FYI - this ticket was triggered by https://www.wikidata.org/w/index.php?title=Wikidata:WikiProject_Source_MetaData/Wikidata_lists/Popular_author_name_strings_on_works_about_topics_that_have_a_Disease_Ontology_ID&oldid=827152222 , which is one element of the disambiguation workflows I am experimenting with. If these things get stable, I am hoping to incorporate their functionality into the Scholia/ Author DIsambiguator system (i.e. without the detour via Listeria).

**Comment by arthurpsmith** [comment]
Done - and yes, this is rather useful for people with common names! Example:
https://tools.wmflabs.org/author-disambiguator/index.php?name=Jun+Wang&doit=Look+for+author&limit=200&filter=wdt%3AP921+wd%3AQ11081&filter_authors=1
