### ISSUE TITLE
Next to the (currently red) topic links, add link to Scholia's /missing page for the topic.

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#32]
e.g. the "hemophilia A" link in https://tools.wmflabs.org/author-disambiguator/?doit=Look+for+author&name=Li%20Li&filter=wdt%3AP921+wd%3AQ2092064 (as per #31 ) would link to https://tools.wmflabs.org/scholia/topic/Q2092064/missing , which links back to the disambiguator.

Making such roundtripping simple (for multiple Scholia/ Author Disambiguator combinations) would probably be a prerequisite for getting larger numbers of people to use these disambiguation workflows.

**Comment by arthurpsmith** [comment]
Nice idea! I guess that scholia page is new?

**Comment by Daniel-Mietchen** [comment]
It's been around for a while: https://github.com/fnielsen/scholia/commits/master/scholia/app/templates/topic_missing.html .

**Comment by arthurpsmith** [comment]
Ok, link added!
