### ISSUE TITLE
Link journals to some useful page

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#37]
Right now, the journal is just given as a string, but it is another unit of curation, so it should be linked somewhere useful.
This could be simply the corresponding /missing page in Scholia ([example](https://tools.wmflabs.org/scholia/venue/Q15749954/missing)) or something else.

**Comment by arthurpsmith** [comment]
Yes, not sure why I didn't at least link to Wikidata the first time around. Anyway, they are linked now, both to wikidata and to the Scholia "missing" page.
