### ISSUE TITLE
Conversion sometimes works only partly 

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#43]
e.g. https://tools.wmflabs.org/author-disambiguator/?name=Ph.+Schwemling&doit=Look+for+author&limit=50&filter=wdt%3AP2093+%22Ph.+Schwemling%22
resulted in just one item being edited, despite 50 having been marked.

**Comment by arthurpsmith** [comment]
Whoah, that's broken. Looking into it now!

**Comment by arthurpsmith** [comment]
Ok, the problem is again coming from the wikidata API - it's not responding or somehow failing to create the entries for most (all but one in this case!) of the manuscripts. I'm relying on that to do the Quickstatements conversion. Hmmm...

**Comment by arthurpsmith** [comment]
Hmm, thought  had a fix for this, but I had to roll it back. Still looking into it...
