### ISSUE TITLE
In author view, provide option not to display co-authors

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#44]
.. or only the three around the target author.

That could help address the issues with many-authored papers.

**Comment by arthurpsmith** [comment]
Ah, I'd been intending to do that, must have forgotten to look there. Thanks.

**Comment by arthurpsmith** [comment]
Ok, I made this change (not really optional, I suppose I could make it an option, but for now it's just not showing all the authors if there are more than 20).
