### ISSUE TITLE
Things look odd if one potential author is a redirect

### ISSUE THREAD

**Issue by arthurpsmith** [arthurpsmith/author-disambiguator#45]
Things seem to display correctly, but the redirected one looks like a duplicate of what it redirects to. Probably should be some display indication of the issue.

**Comment by Kpjas** [comment]
Additionally there's a problem when:

- if you mistakenly choose the redirect, not the actual item
- run the disambiguator
- it removes the author string
- and (rightly) throws and error without creating an author property

I think the situation could be programmatically prevented somehow.

**Comment by arthurpsmith** [comment]
Uh-oh! I'd better get on to fixing this!

**Comment by arthurpsmith** [comment]
I've added a filter clause to the SPARQL query where I think these were coming from that should omit any redirects in future. It's a little hard to test as I think this situation only occurs for a few days after a merge - until Krbot has a chance to change the P50 values to the new author item. I'll keep this open until I get a chance to confirm it's actually working properly for merge/redirect cases.

**Comment by arthurpsmith** [comment]
Nope, didn't work - testing on 'Sachiko Kuroyanagi' right now...

**Comment by arthurpsmith** [comment]
Ok, if you wait for WDQS to catch up my solution does work. However, we can do something better that should work immediately as soon as there's a redirect, by checking the data loaded via the api...

**Comment by arthurpsmith** [comment]
There is info on redirects in the json object that the wikidata library loads - so I'm checking that now. Seems to work well! I've pushed this out live, let me know any further problems... You shouldn't be seeing redirected author items at all now.

**Comment by Kpjas** [comment]
Usefulness of this tool is fantastic! No problems !
