### ISSUE TITLE
Further trouble with many-author papers, even before conversion

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#47]
lots of errors in
https://tools.wmflabs.org/author-disambiguator/?doit=Look+for+author&name=Sandra%20S.%20Padula&filter=wdt%3AP2093+%22Sandra%20S.%20Padula%22&limit=100

**Comment by arthurpsmith** [comment]
Ok, I seem to have broken something....

**Comment by arthurpsmith** [comment]
Hmm, that's odd, I just tried that link and various other combinations (limit=50, limit=200, with or without the filter) and saw no errors at all. Maybe a temporary wikidata API issue? However, I did see the errors earlier today...

**Comment by Daniel-Mietchen** [comment]
Yeah, seems to have been a temporary hickup. I would suspect to be due to the Toolforge, which has been rather fragile lately.
