### ISSUE TITLE
Lowercase search doesn't find uppercase name

### ISSUE THREAD

**Issue by reosarevok** [arthurpsmith/author-disambiguator#54]
A search for articles by Toivo Kallaste (even fuzzy!) didn't find one entered as "TOIVO KALLASTE". I don't think case should ever matter for these things, so maybe it should compare the strings after transforming them to lowercase?

**Comment by arthurpsmith** [comment]
The basic problem is I'm using SPARQL to find matching papers, and the only way to do case-insensitive matching there is with a FILTER which requires comparing 100's of millions of strings - it times out. Finding them via the search API (where strings are normalized for indexing) would work better but I tried that early on and there were other issues - I may go back to that though. Handling this specific case though isn't too hard (and it's relatively common) - I'll look into adding an all-uppercase version of the names for matching purposes.

**Comment by arthurpsmith** [comment]
Ok, I've updated the code to look for upper-case names (only in "fuzzy" search mode though). Other suggestions also welcome!
