### ISSUE TITLE
Fatal error: Maximum function nesting level of '100' reached, aborting! in /data/project/author-disambiguator/public_html/lib/cluster.php on line 20

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#59]
I am getting this for
- https://tools.wmflabs.org/author-disambiguator/?doit=Look+for+author&name=Ashok%20Kumar&filter=wdt%3AP50+wd%3AQ53170226
- https://tools.wmflabs.org/author-disambiguator/?doit=Look+for+author&name=Ashok%20Kumar&filter=wdt%3AP50+wd%3AQ30745113
- https://tools.wmflabs.org/author-disambiguator/?doit=Look+for+author&name=Ashok%20Kumar&filter=wdt%3AP50+wd%3AQ56679154

**Comment by arthurpsmith** [comment]
Oops, checking now.

**Comment by arthurpsmith** [comment]
Hmm - it actually works on my test system (my laptop) but it's really slow. I think the issue is with the large numbers of authors per paper. I will look at tweaking the clustering algorithm to handle this better.

**Comment by arthurpsmith** [comment]
Though those papers with thousands of authors was the reason I created the 'precise_cluster' option - have you tried that?
https://tools.wmflabs.org/author-disambiguator/precise_cluster.php?name=Ashok+Kumar&doit=Look+for+author&limit=50&filter=wdt%3AP50+wd%3AQ30745113

**Comment by Daniel-Mietchen** [comment]
I have played with that option (also with multiple authors ) but wanted to avoid going through the procedure multiple times - I'm coming there from https://www.wikidata.org/wiki/Wikidata:University_of_Virginia/Listeria/UVa_people/Author_name_strings_popular_on_publications_co-authored_by_UVa_people .

Anyway, running a batch now based on the precise clustering: https://tools.wmflabs.org/quickstatements/#/batch/9438 .

**Comment by arthurpsmith** [comment]
Ok - I thought I was being carefully with that recursion, but apparently not quite enough. I've adjusted it, seems to work much better now - give it a whirl!

**Comment by Daniel-Mietchen** [comment]
Yes, seems to work better now - thanks!
