### ISSUE TITLE
option to search only specific name strings

### ISSUE THREAD

**Issue by arthurpsmith** [arthurpsmith/author-disambiguator#61]
fuzzy vs not-fuzzy is too broad - it would be useful to create and run a specific list of name variants you want to search on (full name + abbreviations, but not all versions of abbreviations for example).

**Comment by Daniel-Mietchen** [comment]
I use wdt:P2093 "specific name string" for that.

**Comment by arthurpsmith** [comment]
I've done that too - however that only gets one variant at a time; also that doesn't work if there are additional versions you want to catch that can't be captured by a single originating name string. The case of quotes vs. apostrophe characters used in names like O'Brian for example.

**Comment by arthurpsmith** [comment]
Latest commit adds this capability! Click on the "Specify name strings" checkbox, and then you can adjust the searched names in the text box (one per line).
