### ISSUE TITLE
Apparently completely off-track "potential author"

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#62]
Right now, an [Author Disambiguator search for "Jon-Patrick Allem"](https://tools.wmflabs.org/author-disambiguator/?doit=Look+for+author&name=Jon-Patrick%20Allem) suggests [Emilio Ferrara (Q40463077)](https://www.wikidata.org/wiki/Q40463077) as the potential author.
Not sure where the problem is &mdash; perhaps some failed merge somewhere?

**Comment by arthurpsmith** [comment]
@Daniel-Mietchen It appears to be because of the "stated as" strings on these items: Q38657355 , Q47274027 , and Q57202956 . Which were added by you via sourcemd. Not sure what happened but if somebody fixes those 3 items then this shouldn't happen again. The potential author match uses "stated as" strings to attempt to match up author items.

**Comment by Daniel-Mietchen** [comment]
Looks like the ORCID on [Emilio Ferrara (Q40463077)](https://www.wikidata.org/wiki/Q40463077) was the one for Jon-Patrick Allem, which did not have an item yet. Should be fixed now:
- https://www.wikidata.org/w/index.php?title=Q40463077&type=revision&diff=928933578&oldid=919019582&diffmode=source
- https://www.wikidata.org/w/index.php?title=Q38657355&type=revision&diff=928936673&oldid=903763517&diffmode=source
- https://www.wikidata.org/w/index.php?title=Q47274027&type=revision&diff=928939486&oldid=849192204&diffmode=source
- https://www.wikidata.org/w/index.php?title=Q57202956&type=revision&diff=928940315&oldid=854835320&diffmode=source

Scholia for Emilio: https://tools.wmflabs.org/scholia/author/Q40463077
Scholia for Jon: https://tools.wmflabs.org/scholia/author/Q63391398

**Comment by Daniel-Mietchen** [comment]
Emilio also had another item (Q51794027) with the correct ORCID. Merged: https://www.wikidata.org/w/index.php?title=Q40463077&type=revision&diff=928951200&oldid=928933578&diffmode=source .
