### ISSUE TITLE
Add option to search in a case-neutral way

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#64]
E.g. https://www.wikidata.org/wiki/Q56929444 has all its author name strings given in all-caps, which are currently not picked up.

I think it would make sense to have case-neutral search be the default, ideally with case-sensitive options.

**Comment by arthurpsmith** [comment]
@Daniel-Mietchen - if you select the "fuzzy" option, it should include upper-case versions in the matching process. But I'd be open to making that a default, or add a separate case-sensitivity option... There's a bit of a problem making it entirely case-insensitive in that it's using SPARQL, which doesn't have a case-insensitive string matching option built in. The other option is to use the wikibase search API, but that doesn't have any mechanism for filtering by P31 value, so you get back every matching paper as well as the matching authors, and limiting and re-filtering that list in a reasonable manner gets very hard (that's actually what I started with before switching to SPARQL queries). So - no good solution at the moment here for general case insensitive searches.

**Comment by Daniel-Mietchen** [comment]
You could case-normalize the input string in PHP and then match it in SPARQL. Not sure what you have in mind with "filtering by P31 value", so here is something that I think should work if the input string was lowercased to "robin engler", e.g. via strtolower:

```SPARQL
SELECT DISTINCT ?item ?name
WHERE {
  hint:Query hint:optimizer "None".
{  SERVICE wikibase:mwapi {
    bd:serviceParam wikibase:api "Search";
                    wikibase:endpoint "www.wikidata.org";
                    mwapi:srsearch "\"robin engler\" haswbstatement:P31=Q13442814".
    ?page_title wikibase:apiOutput mwapi:title.
  }
}
  
  BIND(IRI(CONCAT(STR(wd:), ?page_title)) AS ?item)
  
  ?item wdt:P31 wd:Q13442814;
        wdt:P2093 ?name.
  FILTER CONTAINS(LCASE(?name), "robin engler").
}

```

**Comment by Daniel-Mietchen** [comment]
I have not looked into how you've implemented the "fuzzy" option, and I basically avoid it, since I can't direct it usefully, so I am using filtering via P2093 instead, e.g. as [here](https://tools.wmflabs.org/author-disambiguator/?name=John+R.+Smith&fuzzy=1&doit=Look+for+author&limit=500&filter=wdt%3AP2093+%22John+R.+Smith%22).

**Comment by arthurpsmith** [comment]
Oh! It hadn't occurred to me to combine the mwapi with a sparql query, that actually might work. I'll look into it!
Being able to "direct usefully" is partly also my motivation on the other issue regarding having a list of matching strings... but I think the "fuzzy" option works pretty well, I do generally use it myself.

**Comment by arthurpsmith** [comment]
@Daniel-Mietchen I finally got back to this - there's a new "Wikibase search?" checkbox at top, if you select that then it looks for all variations of the name through a method pretty much the same as you suggest above.

**Comment by Daniel-Mietchen** [comment]
Just a brief note that this seems to work fine &mdash; thanks!
