### ISSUE TITLE
Fuzzy searches of Polish names

### ISSUE THREAD

**Issue by Kpjas** [arthurpsmith/author-disambiguator#65]
Generally I've been using __Author Disambiguator__ to work with Polish names [Polish alphabet](https://en.wikipedia.org/wiki/Polish_alphabet). 

It might help me (and perhaps with other languages) to include in fuzzy searches a simple transliteration that is very often used to make Polish names legible in English for example:
Józef Życiński &rarr; Jozef Zycinski
so 
ó &rarr; o
Ż &rarr; Z
ń &rarr; n
Now I do it manually to "catch" more author strings. It seems a good candidate to include this fuzziness in the code.

**Comment by arthurpsmith** [comment]
Makes sense - I'll look into it. Obviously not just applicable to Polish!

**Comment by arthurpsmith** [comment]
Looking into this now - 'Bożena Łozowicka' seems a good test case.

**Comment by arthurpsmith** [comment]
Well, that was trickier than I expected (php had to be updated and also requires a "locale" setting to do this correctly). However, it looks like it's working now! Closing...
