### ISSUE TITLE
Add hyphenated variants for fuzzy match

### ISSUE THREAD

**Issue by Antony-22** [arthurpsmith/author-disambiguator#75]
Items imported from the NIOSHTIC database tend to have hyphenated variants of the author name string.  For example, "John Q. Public" is often listed as "Public-JQ" or "Public-J".  It would be great if these variants could be recognized by the fuzzy match.

In addition, the fuzzy match appears to not catch strings of the form "J.Q Public" or "J.Q. Public", where there is no space immediately after the first period.

Great job on this tool, I find it extremely useful!

**Comment by arthurpsmith** [comment]
Thanks for the suggestion - if you have a specific real case I can test on that might be helpful; this seems like a straightforward thing to fix but it's always good to verify that it works!

**Comment by arthurpsmith** [comment]
Found an example - "Reynolds-JS" - will work on this now!

**Comment by arthurpsmith** [comment]
Ok, I've added matches for the two cases of "Reynolds-JS/Reynolds-J" and "J.S Reynolds" (actual example there was "J.D Smith"). "J.S. Reynolds" should already be caught by the existing fuzzy matches. This is another situation though where it might be better to address issue #61 !
