### ISSUE TITLE
Let title link point to work_item instead of Wikidata directly

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#80]
i.e. replace wikidata_link with the "Full author list" link [everywhere it occurs](https://github.com/arthurpsmith/author-disambiguator/search?q=%22Full+author+list%22&unscoped_q=%22Full+author+list%22).

This seems in line with the tool's practice of presenting an overview page rather than direct links to Wikidata, and it is perhaps a bit less confusing (albeit less easy to discover) than having the "Full author list" link after the - often complete - list of authors and author name strings.

**Comment by arthurpsmith** [comment]
Yeah, that makes sense. Will look at it shortly.

**Comment by arthurpsmith** [comment]
I've made this change on the "oauth" versions...

**Comment by Daniel-Mietchen** [comment]
Works fine.

**Comment by arthurpsmith** [comment]
Closing...
