### ISSUE TITLE
Bug: Li Li uses too much memory

### ISSUE THREAD

**Issue by arthurpsmith** [arthurpsmith/author-disambiguator#9]
Error when trying this author name:
Fatal error: Allowed memory size of 1572864000 bytes exhausted (tried to allocate 64 bytes) in /data/project/author-disambiguator/public_html/magnustools/wikidata.php on line 331

Any way to fix this???

**Comment by arthurpsmith** [comment]
Some thoughts:

1. It probably isn't useful to display thousands of papers for an author - perhaps the paper fetch should be limited (to about 1000?) - that there are more should be indicated somehow!
2. Better would be to present an interface to "refine" the search - search for papers with this author in certain journals, or papers by this author and another named coauthor perhaps?

**Comment by Daniel-Mietchen** [comment]
I'd go for option two and have just opened #17 for that.

**Comment by arthurpsmith** [comment]
Or maybe both? :) Thanks for the suggestions!

**Comment by Daniel-Mietchen** [comment]
Indeed, both would be good.
By the way, it's not just "Li Li" &mdash; here is a list with further test cases: https://tools.wmflabs.org/scholia/venue/Q564954/missing .

**Comment by arthurpsmith** [comment]
I implemented the paper limit (to 900) i.e. option 1 here, and "Li Li" now works. I'll close this and pursue option 2 implementation via #17

**Comment by arthurpsmith** [comment]
I saw it too, it looks like one of the papers with many resolved authors didn't fetch all the author items properly. Maybe a glitch in fetching data via the API somewhere? I could probably add a filter to at least avoid the whole page crashing in that case at least.
