### ISSUE TITLE
In OAuth version, provide a way to retry failed edits

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#91]
When I am doing more than about 2 batched in parallel, I am getting lots of error messages of the ```update failed!?Error code: failed-save``` sort. It would be really useful to be able to go back to those edits and retry them.

Sample output:
<code>
Processing requests....

    Q64072313: Author added to work
    Q64134822: Author added to work
    Q59756250: Author added to work
    Q55011605: Author added to work
    Q33916948: Author added to work
    Q40129087: Author added to work
    Q38718321: Author added to work
    Q43843244: Author added to work
    Q40348093: Author added to work
    Q28388011: Author added to work
    Q40976918: Author added to work
    Q36479003: Author added to work
    Q36281408: Author added to work
    Q36112066: Author added to work
    Q35151429: update failed!?Error code: failed-save
    Q34634823: update failed!?Error code: failed-save
    Q34690314: update failed!?Error code: failed-save
    Q34857132: update failed!?Error code: failed-save
    Q34061654: update failed!?Error code: failed-save
    Q35089506: update failed!?Error code: failed-save
    Q34018979: update failed!?Error code: failed-save
    Q29417036: update failed!?Error code: failed-save
    Q37460866: update failed!?Error code: failed-save
    Q35049194: update failed!?Error code: failed-save
    Q37304332: Author added to work
    Q28385161: Author added to work
    Q37678129: Author added to work
    Q37635891: Author added to work
    Q34625898: Author added to work
    Q36398650: Author added to work
    Q21144927: Author added to work
    Q35883621: Author added to work
    Q35198557: Author added to work
    Q28388293: Author added to work
    Q28388947: Author added to work
    Q28385473: Author added to work
    Q33741198: Author added to work
    Q37633197: Author added to work
    Q37629778: Author added to work
    Q37525139: Author added to work
    Q34088741: Author added to work
    Q37446120: Author added to work
    Q37678142: Author added to work
    Q36448682: update failed!?Error code: failed-save
    Q43605574: update failed!?Error code: failed-save
    Q51918659: update failed!?Error code: failed-save
    Q35902074: update failed!?Error code: failed-save
    Q38518087: update failed!?Error code: failed-save
    Q40332973: update failed!?Error code: failed-save
    Q40389397: update failed!?Error code: failed-save
    Q25256773: update failed!?Error code: failed-save
    Q33885496: update failed!?Error code: failed-save
    Q22306132: update failed!?Error code: failed-save
    Q36165005: update failed!?Error code: failed-save
    Q36164987: update failed!?Error code: failed-save
    Q28391735: update failed!?Error code: failed-save
    Q50265132: update failed!?Error code: failed-save
    Q34619648: update failed!?Error code: failed-save
    Q35164353: update failed!?Error code: failed-save
    Q26823611: update failed!?Error code: failed-save
</code>

**Comment by arthurpsmith** [comment]
Yeah, sorry about that. I did label this experimental! :)
I think to handle this - and also to show it with a progress-bar or something else rather than just a long wait before it returns - I need to start hooking up to the database the tools server provides. That was definitely on my plans for the future but it's going to take a bit of time...

**Comment by Daniel-Mietchen** [comment]
As a workaround to handle these error messages, I am just pressing the "Link selected works to author" button again, which may well result in error messages again, but typically on other items, and if the edit was already OK in the first try, no new edit is made, so 2-3 retries have usually done the trick. Yes, having some utilities like progress bar and such would be nice, and I understand that this takes a bit of time.

**Comment by arthurpsmith** [comment]
Note I have installed a version that sends "name" updates to a background job - however, there is a problem with the process id's hanging around even after they have finished (or been killed) which I need to sort out!

**Comment by arthurpsmith** [comment]
Ok, the batch process going zombie after finishing problem isn't solved, but I can detect and work around it - I'll probably need to regularly restart the server to clean them up though! Anyway, I think this is working... probably some more adjustments will be needed but let's open new issues for those, thanks!

**Comment by Daniel-Mietchen** [comment]
These errors still occur frequently. Two typical scenarios for me (both in OAuth, as the non-OAuth version is basically not usable any more):
- running more than one Author Disambiguator processes in parallel
- running an Author Disambiguator process in parallel to QuickStatements (batch mode, so usually a maximum of two parallel processes)

**Comment by arthurpsmith** [comment]
Hi @Daniel-Mietchen - you know you can rerun batches where errors occurred, right? Just click on the Batches link at top left, hit the link to "Reset errors?", then "Restart batch".
