### ISSUE TITLE
Provide a way to navigate from homepage to the different curation workflows

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#95]
Currently, the homepage (i.e. index.php) features only the author name string as a starting point, but by now, an author item or a work item could be starting points as well, and this should be reflected on the homepage. 

In the long run, we might get additional starting points (journal, organization, topic or even date), so this should be kept in mind.

**Comment by arthurpsmith** [comment]
I updated the "navigation bar" on all the pages so they link to "Names" "Authors" or "Works" - the various starting pages for those different workflows. If we add journals or topics etc. it should fit in nicely...
