### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function getLabel()

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#98]
Currently getting this error

```
Fatal error: Uncaught Error: Call to a member function getLabel() on null in /data/project/author-disambiguator/public_html/work_item.php:145 Stack trace: #0 {main} thrown in /data/project/author-disambiguator/public_html/work_item.php on line 145
```

at
https://tools.wmflabs.org/author-disambiguator/work_item.php?id=Q73832354&doit=Get+author+links+for+work .

**Comment by Daniel-Mietchen** [comment]
Another example: 
https://tools.wmflabs.org/author-disambiguator/work_item.php?id=Q36491273&doit=Get+author+links+for+work

**Comment by Daniel-Mietchen** [comment]
Just ran into this again and took a screen shot:

<img width="1133" alt="Screen Shot 2019-11-29 at 17 00 35" src="https://user-images.githubusercontent.com/465923/69891330-d1742e00-12c9-11ea-934a-05e4c2dd8421.png">

**Comment by Daniel-Mietchen** [comment]
I suspect this has to do with the item having been freshly curated but not yet available through SPARQL due to server lags.

**Comment by arthurpsmith** [comment]
I am assuming you haven't run into this recently? In the "Oauth" version I believe I'm always catching these null responses and handling them somehow, rather than leaving an uncaught error.
